name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.spi.yml'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macOS-15
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 26.2
        run: sudo xcode-select -s /Applications/Xcode_26.2.app/Contents/Developer
      - name: Test
        run: set -o pipefail && swift test | xcbeautify --renderer github-actions
